[workspace]
resolver = "2"
members = [
	"crates/*",
	"examples/*",
	"tasks/*",
]

[workspace.package]
authors = ["Boshen <boshenc@gmail.com>"]
description = "The JavaScript Oxidation Compiler"
edition = "2021"
homepage = "https://github.com/Boshen/oxc"
keywords = ["JavaScript", "TypeScript", "compiler", "parser"]
license = "MIT"
repository = "https://github.com/Boshen/oxc"
version = "0.0.0"

[workspace.dependencies]
jemallocator = "0.5.0"
mimalloc = "0.1.34"
bitflags = "1.3.2"
bumpalo = "3.12.0"
compact_str = "0.7.0"
miette = "5.6.0"
rayon = "1.7.0"
rustc-hash = "1.1.0"
serde = "1.0.156"
serde_json = "1.0.94"
thiserror = "1.0.39"
clap = "4.1.8"
indextree = "4.6.0"
glob = "0.3.1"
lazy_static = "1.4.0"


[profile.release]
# Configurations explicitly listed here for clarity.
# Using the best options for performance.
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
debug = false
panic = "abort" # Let it crash and force ourselves to write safe Rust.

# Use the `--profile release-debug` flag to show symbols in release mode.
# e.g. `cargo build --profile release-debug`
[profile.release-debug]
inherits = "release"
strip = false
debug = true
